### ISSUE TITLE
OwnedGamesResultModel returns null properties

### ISSUE THREAD

**Issue by theaswanson** [babelshift/SteamWebAPI2#101]
I'm trying to use the PlayerService to return my list of games. I get my list of games back, but several of the OwnedGameModel properties are null, including Name, ImgIconUrl, and ImgLogoUrl.

Here's my code:
```
public async Task < IActionResult > Get(ulong id) {
    var webInterfaceFactory = new SteamWebInterfaceFactory("my api key");
    var steamInterface = webInterfaceFactory.CreateSteamWebInterface < PlayerService > (new HttpClient());
    var response = await steamInterface.GetOwnedGamesAsync(id);
    var games = response.Data;
    return Ok(games);
}
```

Sample result:
![image](https://user-images.githubusercontent.com/25459801/83982114-cdb50a00-a8f1-11ea-8b15-b9c93e392207.png)

**Comment by babelshift** [comment]
@theaswanson the `IPlayerService/GetOwnedGames` endpoint will, by default, only return `appid` and playtime stats. You will need to set the `includeAppInfo` parameter to `true` to include other information about the owned games. That's just how Valve setup this endpoint. Please let me know if that resolves your issue.

**Comment by theaswanson** [comment]
Ah, my bad. I didn't look at the rest of the optional parameters:
`GetOwnedGamesAsync(ulong steamId, bool? includeAppInfo = null, bool? includeFreeGames = null, IReadOnlyCollection<uint> appIdsToFilter = null);`
I'm sure that'll fix my issue. I'll give it a shot and see if it works.

**Comment by theaswanson** [comment]
I was able to fix my issue by changing my code like this:
```
public async Task < IActionResult > Get(ulong id) {
    ...
    var response = await steamInterface.GetOwnedGamesAsync(id, true, true);
    ...
}
```
