### ISSUE TITLE
Bug with SteamId().ToLegacyFormat()

### ISSUE THREAD

**Issue by AlfieJPalmer** [babelshift/SteamWebAPI2#103]
I've written a function to convert a Legacy Steam ID (STEAM_X:Y:Z) to the SteamId type in the API but noticing a small discrepancy.
Ref: _https://developer.valvesoftware.com/wiki/SteamID_

Consider the following Legacy Steam ID:
**STEAM_0:1:123**

Universe (X):       0   -> [Individual / Unspecified]
ID Part (Y):        1   -> [Individual]
Account Number (Z): 123

SteamId32: 247 (2 * 123 + 1)

If I create a SteamId() with the following as
var sid = new SteamId(0, 1, 247)

I get the following from:
sid.To64Bit() ==         4503603922338039 (**wrong**)
sid.ToLegacyFormat() == "STEAM_0:1:123"   (correct)
sid.ToModernFormat() == "[U:0:247]"       (correct)

I notice that the SteamWebAPI2.Models.SteamUniverse Enum specifies 0=Invalid, which is wrong, so I modified my call to set it to Public:
var sid = new SteamId(1, 1, 247)

I get the following from:
sid.To64Bit() ==         76561197960265975 (correct)
sid.ToLegacyFormat() == "STEAM_1:1:123"    (**wrong**)
sid.ToModernFormat() == "[U:0:247]"        (correct)

I believe the issue here is around the SteamUniverse enum, 0 and 1 correspond to Individual / Unspecified / Public account.
Could you please advise?

**Comment by babelshift** [comment]
@AlfieJPalmer my understanding is that Universe 0 is not valid because it's no longer used in "new" Steam2 representations of Steam IDs. Most libraries that I have researched to build out my implementation were based on the assumption that Universe 0 will be automatically treated as Universe 1. Do you have any documentation clarifying this?

**Comment by babelshift** [comment]
Closing because no response from reporter.
