### ISSUE TITLE
Ensure default language 'en_us' used for all requests

### ISSUE THREAD

**Issue by SeeD-Seifer** [babelshift/SteamWebAPI2#11]

**Comment by babelshift** [comment]
Sorry for the super late response.

I thought the default is always en_us? There are some methods that allow for language parameters, but are always optional.

Please let me know if this is not the case.

**Comment by SeeD-Seifer** [comment]
The default language is NOT **en_us**. For example if you get Dota heroes with default language, the result is different from **en_us**.

Actually, I just need ```DOTA2Match.GetLeagueListingAsync``` method with language parameter, because it has description field, which is language dependent.
But I thought it make sense to use **en_us** language for all requests, if another does not specified.

**Comment by babelshift** [comment]
Thanks for the clarification.

**Comment by babelshift** [comment]
I'm starting this process now. Commit ca2ec9e8940504b334e31c92ff1be16f0a26e7c4 introduced default "en_us" language for GetHeroes, GetGameItems, and GetLeagueListing methods.
