### ISSUE TITLE
Dota web api -> GetMatchDetails response issue

### ISSUE THREAD

**Issue by Dmitriy-ksm** [babelshift/SteamWebAPI2#120]
GetMatchDetails has recently been updated. Added new fields to the answer. 
For MatchPlayer - net_worth, aghanims_scepter, aghanims_shard, moonshard. 
And for MatchDetailResult - flags (to be honest, now I have no idea what this field is responsible for, but since the server returns it, it may have a use.).
Also, some characters (as far as I know, there are only 3 of them - Lone Druid, Arc Warden and Meepo) for MatchPlayer have an additional_units field. Its usefulness is questionable for Meepo & Warden, but may be useful when we talk about Lone Druid or AD mode with Lone Druid skills in 
![MatchPlayer - 'net_worth aghanims_scepter aghanims_shard moonshard' fields](https://user-images.githubusercontent.com/57687769/139560257-c2297c4a-8bff-45dd-bb45-16a0d7af5edf.png)
![MatchPlayer - 'additional_unis' field](https://user-images.githubusercontent.com/57687769/139560258-d0c6762d-a013-413e-9333-c3908a517ec0.png)
![MatchDetailResult - 'flags' field](https://user-images.githubusercontent.com/57687769/139560259-76d19eea-b288-4264-8936-3c1d23042dae.png)

**Comment by babelshift** [comment]
@Dmitriy-ksm is this issue now resolved after merging #121? Thanks.

**Comment by Dmitriy-ksm** [comment]
Yes. It might be worth keeping in mind that there is no "flags" field in the MatchDetailResult when merging 121. I'll leave it (Add field to answer or not) up to you. The problem can be closed
