### ISSUE TITLE
NuGet install fails because it requires NuGet 3.0<

### ISSUE THREAD

**Issue by Autositz** [babelshift/SteamWebAPI2#13]
Installing the Package fails due to missing NuGet dependencies.

SteamWebAPI2 requires AutoMapper which requires Microsoft.CSharp 4.0.0 which requires NuGet 3.0

`PM> Install-Package SteamWebAPI2 
Attempting to resolve dependency 'AutoMapper (≥ 4.2.1)'.
Attempting to resolve dependency 'Microsoft.CSharp (≥ 4.0.0)'.
Install-Package : The 'Microsoft.CSharp 4.0.0' package requires NuGet client version '3.0' or above, but the current NuGet version is '2.8.60318.667'.
Bei Zeile:1 Zeichen:16
- Install-Package <<<<  SteamWebAPI2 
  - CategoryInfo          : NotSpecified: (:) [Install-Package], NuGetVersionNotSatisfiedException
  - FullyQualifiedErrorId : NuGet.NuGetVersionNotSatisfiedException,ICSharpCode.PackageManagement.Cmdlets.InstallPackageCmdlet
    `

How to get SteamWebAPI2 without NuGet 3.0?
I tried to update NuGut by doing "nuget.exe update -self" and it told me it updated it, but i still get the same error. ;)

**Comment by babelshift** [comment]
Hi Autositz. Thanks for the issue. Sorry for the slow response. I just started a new job recently, so I will be slow working on this. But I will try to keep you updated on progress!

**Comment by jpreese** [comment]
Autositz, are you running this from within Visual Studio?  When you open the package manager, it should tell you what version of NuGet you're running on. For example:

Package Manager Console Host Version 3.3.0.167

I just want to make sure that the update actually stuck.  I just tried running Install-Package on a new project and all of the dependencies resolved for me.

**Comment by babelshift** [comment]
Is this still an issue? Please let me know. Thanks.

**Comment by babelshift** [comment]
Please re-open this issue if it remains. Thanks.
