### ISSUE TITLE
SteamWebInterfaceFactory broken in .NET 7

### ISSUE THREAD

**Issue by BowDown097** [babelshift/SteamWebAPI2#132]
Upgraded my project to .NET 7, now I get this exception upon using the SteamWebInterfaceFactory(string) constructor.
[e.txt](https://github.com/babelshift/SteamWebAPI2/files/10003416/e.txt)

**Comment by Longoon12000** [comment]
PR #133 fixes this, please merge and deploy!

**Comment by ablizorukov** [comment]
Hi, have the same issue, have a lool please and merge 🚀

**Comment by emmanuelrflores** [comment]
Any chance to get this issue merged?

**Comment by babelshift** [comment]
Thanks and sorry for the delay. Check out NuGet package 4.4.1.
