### ISSUE TITLE
GetMatchHistoryBySequenceNumberAsync wrong model?

### ISSUE THREAD

**Issue by Hapseleg** [babelshift/SteamWebAPI2#14]
Hi, I might be wrong but isn't the method GetMatchHistoryBySequenceNumberAsync returning an object of a wrong class? What I get returned is an object matching the one I get from GetMatchHistoryAsync while GetMatchHistoryBySequenceNumberAsync should have returned the one matching GetMatchDetailsAsync.

**Comment by babelshift** [comment]
Hi Hapselag. Thanks for the report. I started a new job recently, so I
might be slow to respond. I will check on this tonight if I can.

**Comment by Hapseleg** [comment]
Great :) thanks a lot, no rush! Pretty sure the thing you have to change is in DOTA2Match.cs, AutoMapperConfiguration.cs and in MatchHistoryBySequenceNumberResultContainer.cs but I'm not 100% sure. 
Once again thanks for making the library and no rush :)

**Comment by babelshift** [comment]
OK after looking at this, it's a bit complicated.

The Steam Web API endpoint for `MatchHistoryBySequenceNumber` returns the following data:

  * Status
  * NumResults
  * TotalResults
  * ResultsRemaining
  * List of Matches

My method `GetMatchHistoryBySequenceNumberAsync` returns only the List of Matches from the above result set. So while technically the important part of the results is being returned, it's not all of the results.

I will try to change the method to return the full data set when I get a chance, but you should be able to use the method as is for the majority of cases.

**Comment by Hapseleg** [comment]
Hmm I might be doing something wrong? Here's what I got
```
public async Task<IReadOnlyCollection<MatchHistoryMatchModel>> GetMatchHistoryBySequenceNum(long? startAtMatchSequenceNumber = null, int? matchesRequested = null)
        {
            var steamInterface = new DOTA2Match( steamWebApiKey );
            


            var a = await steamInterface.GetMatchHistoryBySequenceNumberAsync( startAtMatchSequenceNumber: startAtMatchSequenceNumber, matchesRequested: matchesRequested );

            return a;
        }
```
startAtMatchSequenceNumber = 2003044685 and matchesRequested = 100

I'll paste the first one I get returned:
```
-		[0]	{Steam.Models.DOTA2.MatchHistoryMatchModel}	Steam.Models.DOTA2.MatchHistoryMatchModel
		DireTeamId	0	int
		LobbyType	7	int
		MatchId	2285301171	long
		MatchSequenceNumber	2003044685	int
+		Players	Count = 10	System.Collections.Generic.IReadOnlyCollection<Steam.Models.DOTA2.MatchHistoryPlayerModel> {System.Collections.Generic.List<Steam.Models.DOTA2.MatchHistoryPlayerModel>}
		RadiantTeamId	0	int
+		StartTime	{10-04-2016 08:42:47}	System.DateTime

```

But if I try calling the GetMatchHistoryBySequenceNum from my browser like so:
http://api.steampowered.com/IDOTA2Match_570/GetMatchHistoryBySequenceNum/v1?start_at_match_seq_num=2003044685&matches_requested=100&key=<KEY>

I get returned something that matches what I would get if I use GetMatchDetails and another odd thing is that GetMatchHistoryBySequenceNum never returns the DireTeamId and RadiantTeamId so somehow it makes a GetMatchHistory call?

Thanks once again :)

**Comment by babelshift** [comment]
OK after re-reading this and looking at the results, you are correct. Something here is wrong. I will try to fix this today.

**Comment by babelshift** [comment]
Bad news. My main partition suffered a power loss and is thus rendered inoperable at the moment. I'm going to deal with that and then this.

**Comment by Hapseleg** [comment]
Wauw that sucks, hope you didn't lose any important data.

**Comment by babelshift** [comment]
@Hapseleg Nope. No data loss. I should be recovered and able to fix this today.

**Comment by babelshift** [comment]
OK just pushed a fix for this in the latest nuget package. Please let me know if it helps.

**Comment by Hapseleg** [comment]
Thanks a lot :) will let you know how it works on monday

**Comment by Hapseleg** [comment]
That did the trick :) thanks once again and have a nice day.
