### ISSUE TITLE
Problems with AutoMapper

### ISSUE THREAD

**Issue by felaugmar** [babelshift/SteamWebAPI2#16]
I'm trying to use the library and getting some errors in the AutoMapper lib;

If I use the version AutoMapper version 5.0.2, i'm getting this error:
`Could not load type 'AutoMapper.IMapperConfiguration' from assembly 'AutoMapper'`
`at SteamWebAPI2.AutoMapperConfiguration.Initialize()`

and if I use the version 4.2.1, it tries to load the 5.0.2 and get an error loading an inexistent .dll

**Comment by babelshift** [comment]
Sorry I didn't see this before. Did you get your issue resolved? I think I fixed this recently.

**Comment by jirwong** [comment]
Sorry, this wasn't the proper fix; I initially thought it was mapping to the wrong type but after a bit more investigation, it was the custom JSON serializer that was returning the wrong type instead.

See my other pull request for the fix. :)

**Comment by Amethi** [comment]
I had this today. The newer versions of AutoMapper don't have this interface in. I had to downgrade Automapper via NuGet. Either the project needs updating to support the newest version of AutoMapper or the NuGet package needs constraining to AutoMapper 4.2.1.

**Comment by Amethi** [comment]
@felaugmar, you probably don't have the right binding redirect in your config file. It should read: <bindingRedirect oldVersion="0.0.0.0-4.2.1.0" newVersion="4.2.1.0" />

**Comment by babelshift** [comment]
I forced a specific AutoMapper version on commit beb2eb13a1e72774a2c7cc7f69a0cffce7b7e6b4. Thanks for the heads up.
