### ISSUE TITLE
member count for ProfileGroup should be more than 65535

### ISSUE THREAD

**Issue by jirwong** [babelshift/SteamWebAPI2#17]
Was doing some work on the steam groups, and found an issue.

Seems like there are steam groups with more than 65535; currently the field in ProfileGroup is a ushort, but I'd suggest it to be uint instead due to large numbers in some steam groups instead.

It affects a few methods, but personally I think the most affected one is GetCommunityProfileAsync (for me anyway).

Pretty simple fix by changing the field like below in ProfileGroup : 

public uint MemberCount { get; set; } // as opposed to ushort

Anyway, just fyi. :)

**Comment by babelshift** [comment]
Thanks. Fixed on commit abf094cbea016eaf2097aee784777932075a5e19.
