### ISSUE TITLE
Add .NET 4.5.2 target

### ISSUE THREAD

**Issue by kamranayub** [babelshift/SteamWebAPI2#2]
This is the kind of library I was looking for. I almost rolled it myself but I need async/await and a quick and easy interface so this fits the bill. I can't install the Nuget package because I have a 4.5.2 project.

**Comment by babelshift** [comment]
@kamranayub Thanks for poking me on this issue. The library doesn't take advantage of anything in .NET 4.6 yet anyway, so I will have no problems downtargeting. I will have this done within a day. Thanks again.

**Comment by kamranayub** [comment]
No problem, I plan to go to bed tonight and use this tomorrow. I can always compile locally for now. I did this just yesterday for my own project, if you want to see how:

https://github.com/kamranayub/GiantBomb-CSharp/commit/70ce2b36161572c7081921d03f433eadbb6882ec

1. Add new projects targeting different framework(s)
2. Rename the assemblies to be the same name (optional)
3. Change build output for Debug/Release to central directory (e.g. `../build/Debug/net*`)
4. Share assembly info (looks like Appveyor might do this anyway?) so all of them have the same versions
5. Add additional Nuget lib targets to nuspec file

**Comment by babelshift** [comment]
Should be done on this commit: https://github.com/babelshift/SteamWebAPI2/commit/3e9ba1824d3863e3ebadcd42175cfa4d500457a8

Also pushed the new nuget package. Try it out when you get a chance.

**Comment by kamranayub** [comment]
Yup it works! Thank you.
