### ISSUE TITLE
Standardized steamId throughout the functions

### ISSUE THREAD

**Issue by jirwong** [babelshift/SteamWebAPI2#21]
Hey there,

I was using a few functions and the parameter steamId seems to vary between a string or a ulong. Perhaps standardizing it or creating an overload method to handle this?

Just a thought. :)

**Comment by babelshift** [comment]
Can you provide some examples? I'm not aware of any SteamID parameters that will be strings.

**Comment by jirwong** [comment]
My mistake; I was looking at my own fork and I messily made some changes there, master fork is fine.

Sorry for the false alarm.
