### ISSUE TITLE
Merge not worked?

### ISSUE THREAD

**Issue by Amethi** [babelshift/SteamWebAPI2#22]
This pull request was merged back in May, but it doesn't seem to have actually been committed?
https://github.com/babelshift/SteamWebAPI2/pull/15

For instance, I can't see GetPlayerSummariesAsync() in:
https://github.com/babelshift/SteamWebAPI2/blob/master/SteamWebAPI2/Interfaces/ISteamUser.cs

**Comment by babelshift** [comment]
Strange. I'll investigate tonight. Thanks.

**Comment by babelshift** [comment]
Thanks for pointing this out. Fixed on commit: 1461a158c33d10444fcc460396bb99cfb6ef1df6

**Comment by Amethi** [comment]
Awesome, thanks!
