### ISSUE TITLE
Support .NET Core

### ISSUE THREAD

**Issue by Goz3rr** [babelshift/SteamWebAPI2#23]
Any plans for this?

**Comment by babelshift** [comment]
I would love to when I get some time to learn what is necessary. Do you have an immediate need? Curious of what your use case will be.

**Comment by Goz3rr** [comment]
Nothing really short term, but it would be nice to be able to use this with ASP.NET Core.

Doesn't look like it'll require much code changes, both Newtonsoft.Json and Automapper already support it.

**Comment by babelshift** [comment]
.NET Core is now supported in the latest release build (4.0.0).
