### ISSUE TITLE
Error when trying await key.GetCommunityProfileAsync().

### ISSUE THREAD

**Issue by Tvde1** [babelshift/SteamWebAPI2#24]
I know this looks more like troubleshooting, but I think this is a bug in your code.

This line crashes for me:

    var communityProfile = await key.GetCommunityProfileAsync(steam64ID);

And I get this:

    Exception thrown: 'System.Runtime.Serialization.SerializationException' in mscorlib.dll

    Additional information: Element inGameServerIP from namespace  cannot have child contents to be deserialized as an object. Please use XmlNode[] to deserialize this pattern of XML.

**Comment by Tvde1** [comment]
Sorry if this isn't the right format for a GitHub issue.

**Comment by babelshift** [comment]
I'll take a look at it. Do you have a Steam ID that you're seeing that fail with? Or is it everything you've tried? Thanks.

**Comment by Tvde1** [comment]
I used the same key and steamid that I used to get all of my friends list and that worked.

**Comment by babelshift** [comment]
Can you include the Steam ID that you used to produce the error? Don't post your key though.

**Comment by Tvde1** [comment]
Here's my steamID: 76561198050013009.

**Comment by Tvde1** [comment]
So does the error occur for you too?

**Comment by Tvde1** [comment]
Well, I executed the same code and it seems to be fixed. 
If you didn't do anything, just say you fixed it anyways so I won't like an idiot for posting it here lol

**Comment by babelshift** [comment]
Hey sorry. Yesterday was a national holiday in the US. No time to look at
the issue.

I see you closed it. Do you still need help?

**Comment by Tvde1** [comment]
Apparently it is still happening.

**Comment by babelshift** [comment]
Should be fixed on commit 7e3440341e407b26be9d781cda548163de7ba38e. Please confirm.

This was only occurring when the profile in question was connected to an in game server. The "inGameServerIP" serialization was failing due to the wrong type.

**Comment by Tvde1** [comment]
Yeah it's fixed.
