### ISSUE TITLE
ISteamUserAuth

### ISSUE THREAD

**Issue by Abedron** [babelshift/SteamWebAPI2#25]
Missing most importatant call ISteamUserAuth/AuthenticateUserTicket

**Comment by babelshift** [comment]
I can add this, but I don't know how to use/test it. Do you have any idea what the response structure looks like? I only know the request structure.

**Comment by babelshift** [comment]
Possible resolved on commit 279fdb9ec87e71f8d72224abc5cb46bad4a0cd95. Please let me know.
