### ISSUE TITLE
New update doesn't work with AutoMapper.

### ISSUE THREAD

**Issue by Tvde1** [babelshift/SteamWebAPI2#26]
I just updated SteamWebAPI2 to v2.0.0.33 and now it gives me an error whenever I run ` new SteamUser`.

Here's the error:

    Managed Debugging Assistant 'BindingFailure' has detected a problem in '[path]

    Additional information: The assembly with display name 'AutoMapper' failed to load in the 'LoadFrom' binding context of the AppDomain with ID 1. The cause of the failure was: System.IO.FileLoadException: Could not load file or assembly 'AutoMapper, Version=4.2.1.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

And this shows up in my warning list:
`Found conflicts between different versions of the same dependent assembly that could not be resolved. ` In the file at `C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets`.
(btw when I open that file I get 102 warnings lol).

I also can't update AutoMapper because SteamWebAPI2 depends on version 4.2.1.

Any help?

**Comment by Tvde1** [comment]
And yes, of course I have tried reinstalling and installing older versions.

**Comment by babelshift** [comment]
What version of AutoMapper do you have listed in your NuGet Package Manager for your solution?

**Comment by Tvde1** [comment]
v4.2.1.

**Comment by babelshift** [comment]
Strange. I just created a blank console application, installed the latest SteamWebAPI2 NuGet package (2.0.0.33), and I get no warnings or errors. I'll keep investigating.

**Comment by Tvde1** [comment]
Well actually I think it's a problem on my side. I'll try to figure this out.

**Comment by Tvde1** [comment]
Yes it was an error in my `App.config`.

If anyone else might ever get this problem, remove 

      <dependentAssembly>
        <assemblyIdentity name="AutoMapper" publicKeyToken="be96cd2c38ef1005" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.0.0" newVersion="5.2.0.0" />
      </dependentAssembly>

From `App.config`.

Sorry to bother you with this. I know this isn't what issues are for.

**Comment by babelshift** [comment]
Hey dude don't worry about it. This is just a fun side project for me. Any help that I can provide to people is good for me.

Glad you figured it out.
