### ISSUE TITLE
GetFriendsListAsync() returns Unauthorized code 401.

### ISSUE THREAD

**Issue by Tvde1** [babelshift/SteamWebAPI2#27]
Here I am yet again.

I receive an error on:
`friendsList = await key.GetFriendsListAsync(steam64ID);`

There's the message.

    Exception thrown: 'System.Net.Http.HttpRequestException' in mscorlib.dll

    Additional information: Response status code does not indicate success: 401 (Unauthorized).

    If there is a handler for this exception, the program may be safely continued.

The key and the steamId I use seem to be correct after breaking.

Here is the full error:

![image](https://cloud.githubusercontent.com/assets/11540531/20643924/0a13fa3e-b426-11e6-82c5-a897948bde29.png)

EDIT: The API seems to be working when I use `http://api.steampowered.com/ISteamUser/GetFriendList/v0001/?key=[KEY]&steamid=[ID]`.

**Comment by Tvde1** [comment]
I think it occurs when I use the SteamID of someone who has their profile on private.

**Comment by babelshift** [comment]
Can you send me a Steam ID that you know is exhibiting this behavior?

**Comment by Tvde1** [comment]
I was on a server with this guy: `[U:1:1222448]`.
His steam64ID is `76561197961488176`.
As you can see, [his profile](http://steamcommunity.com/id/CaptainGinger/) is private.

I can fix this by checking weather the profile is private or not first,

**Comment by babelshift** [comment]
OK so I've confirmed your suspicions. In fact, the Steam Web API actually returns a 401 unauthorized HTTP response instead of indicating the user's profile is private. I don't agree with their approach since 401 should be reserved for authentication/authorization failures (such as if a Steam Web API key is invalid). 

Regardless, this is the expected behavior. Your solution seems like it would work.

**Comment by Tvde1** [comment]
Yeah I don't think it's upto you guys to do something with this. Maybe add a warning that you have to check the visibility first (with e.g. `if (profile.ProfileVisibility != "Public") { return; }`.
