### ISSUE TITLE
Add interfaces for testability and dependency injection

### ISSUE THREAD

**Issue by kamranayub** [babelshift/SteamWebAPI2#3]
It would be nice to extract interfaces for each of the service implementations so that I can mock them for testability as well as for dependency injection.

**Comment by babelshift** [comment]
Good idea. I haven't had a chance to make tests yet since the lib is only a few weeks old.

By the way, I host this site for better documentation on using the Steam Web API (since their documentation -- for lack of a better word -- sucks.

http://steamwebapi.azurewebsites.net/

**Comment by kamranayub** [comment]
I saw that, it's awesome!

**Comment by babelshift** [comment]
Please see commit https://github.com/babelshift/SteamWebAPI2/commit/06bf1b77b957fe8914e52ebd04c8559e4ffadd08 and let me know if this satisfies the request.

**Comment by kamranayub** [comment]
Yup, looks like it will!

I was also caught by an exception the first time I used it where it was expecting an app setting. I would propose including a default constructor that has the HTTPS url, and then allowing people to pass in a new URL as an overload.

```c#
public abstract class SteamInterface {

  protected string _apiUrl = "https://api.steampowered.com";

  ctor(string apiKey, string service) {

  }

  ctor(string apiUrl, string apiKey, string service) :
    this(apiKey, service) {
    this._apiUrl = apiUrl;
  }

}
```

Then all derived classes have an overloaded constructor that accepts an API URL and key, if desired.

Since this also makes it easier/portable between classes when using dependency injection instead of forcing reliance on an app setting (this way I can provide a URL through whatever means makes sense to my app).

**Comment by babelshift** [comment]
Yes, in fact, I meant to address that issue but never did. I'm glad someone else is starting to use this library so I can get off my lazy ass :+1:

**Comment by kamranayub** [comment]
I totally get it! This has been working great for me so far, I'll let you know if I run into anything else.
