### ISSUE TITLE
FYI:  JSON integer 4294967295 is too large or small for an Int32 at Achievements

### ISSUE THREAD

**Issue by nfMalde** [babelshift/SteamWebAPI2#30]
Hi,

Since you are using Steam.Models and I allready created a issue there, this is more or less a information.

At APP ID 240 if you are trying to  get the acheivements you getting the error above.

See: https://github.com/babelshift/Steam.Models/issues/10

![steammodelserror](https://cloud.githubusercontent.com/assets/5366984/21164583/43f78dfc-c19a-11e6-9f92-00b974c3b490.png)

Best,

Malte

**Comment by babelshift** [comment]
Thanks. I'll check on this one too (like your other issue).

**Comment by babelshift** [comment]
Should be fixed on the latest Steam.Models nuget package. Let me know.
