### ISSUE TITLE
`GetSchemaAsync()` mapping error with TF2 items.

### ISSUE THREAD

**Issue by Tvde1** [babelshift/SteamWebAPI2#31]
Upon executing 

    var econItems = new EconItems(key, EconItemsAppId.TeamFortress2);
    var x = await econItems.GetSchemaAsync();

I'm getting this error:
![image](https://cloud.githubusercontent.com/assets/11540531/21288129/5e4cc10c-c47b-11e6-8691-9280d2efda95.png)

The error is happening in `EconItems.cs` at line 95:

    var schemaResult = await CallMethodAsync<SchemaResultContainer>("GetSchema", 1, parameters);

gg plz fix

**Comment by Tvde1** [comment]
Your `Steam.Models/GameEconomy/SchemaQualitiesModel.cs` seems to be fine. I don't get why the error lists `Steam.Models/DOTA2/SchemaQualityModel.cs`.

**Comment by Tvde1** [comment]
Could it be that it's trying to get DOTA 2's item schema?

**Comment by Tvde1** [comment]
It might be trying to get DOTA 2's item schema. When I hover over the `var`, it shows this.

![image](https://cloud.githubusercontent.com/assets/11540531/21288219/24efa2ec-c47d-11e6-9d5f-4b6c9af5406f.png)

**Comment by Tvde1** [comment]
It might be because the two files are both called `SchemaModel`. This should be an easy fix,

**Comment by babelshift** [comment]
I'll check it out in about 30 mins. Thanks for the heads up.

**Comment by babelshift** [comment]
Looking now.

**Comment by babelshift** [comment]
I'm creating some classes specifically for TF2 schemas. I'll probably have it done tomorrow.

**Comment by Tvde1** [comment]
Thanks!

**Comment by babelshift** [comment]
Added a new method called `GetSchemaForTF2Async` to `EconItems` interface to retrieve a TF2 specific schema. My minimal testing has passed. Let me know how it works for you. Try the latest nuget package.

**Comment by Tvde1** [comment]
Works like a charm :)
