### ISSUE TITLE
 await econItems.GetSchemaForTF2Async() crashes in the latest NuGet package.

### ISSUE THREAD

**Issue by Tvde1** [babelshift/SteamWebAPI2#33]
I had been using this for a week now, but it keeps crashing.

Here's the exception it throws:
![image](https://cloud.githubusercontent.com/assets/11540531/21581113/9f1d6814-d022-11e6-8e1f-67aeace38a1e.png)
I've checked that the Steam API was not having troubles.

**Comment by Tvde1** [comment]
Yeah, with:

                econItems = new EconItems(key, EconItemsAppId.TeamFortress2);
                schemaModel = await econItems.GetSchemaForTF2Async();

`schemaModel` ends up being `null` always.

**Comment by Tvde1** [comment]
Ah never mind. I was trying to use schemaModel before it the async was done.

**Comment by babelshift** [comment]
Just want to confirm, everything is OK with this method so far?

**Comment by Tvde1** [comment]
Yes. It works fine.
