### ISSUE TITLE
Getting playtime returns wrong numbers.

### ISSUE THREAD

**Issue by Tvde1** [babelshift/SteamWebAPI2#34]
So I tried this:

    var games = games = await playerService.GetOwnedGamesAsync(steam64ID, includeFreeGames:true);
    var tf2 = games.OwnedGames.FirstOrDefault(x => x.AppId == 440);
    if (tf2 != null)
    {
        return tf2.PlaytimeForever;
    }

I am getting these values:
![capture](https://cloud.githubusercontent.com/assets/11540531/21581734/a1594c58-d03e-11e6-95af-d4de57749d73.PNG)
While my profile say this:
![real data](https://cloud.githubusercontent.com/assets/11540531/21581735/a8db6916-d03e-11e6-9344-7f2113c5e50a.PNG)
I really don't get this. Should the two playtime variables not be ints?

**Comment by Tvde1** [comment]
Damn I am an idiot. It's the amount in minutes lmao.

**Comment by babelshift** [comment]
Glad you figured it out. I should have actually made those properties `TimeSpan` objects. Maybe I'll add separate properties for that to make it more clear.

**Comment by babelshift** [comment]
Going to re-open this so I can track work to address the comment I made above.

**Comment by babelshift** [comment]
Fixed on commit: b95b20edd23b9940a3b6fa6137e31dae2f4bfceb.
