### ISSUE TITLE
Missing access to HTTP response headers

### ISSUE THREAD

**Issue by stil** [babelshift/SteamWebAPI2#36]
Current design of the library makes it impossible to access HTTP response headers of API call.

For example, call to `IEconItems_440/GetSchema` returns `Last-Modified` header useful for checking if schema have changed. Especially that schema file is huge and comparing it side to side is not the best idea out there.

I'd suggest a change to the API of `ISteamWebInterface`. Instead of
```
var schemaResult = await steamWebInterface.GetAsync<SchemaResultContainer>("GetSchema", 1, parameters);
```
we could do
```
var httpResponse = await steamWebInterface.GetAsync("GetSchema", 1, parameters);
var schemaResult = httpResponse.JSON<SchemaResultContainer>();
var lastModified = httpResponse.Headers.LastModified;
```
So that `GetAsync()` would return a wrapper over `HttpResponseMessage`.

It would be still possible to have one-liners where accessing HTTP headers is not required.

**Comment by babelshift** [comment]
Thanks for the issue. I'll consider this as I shift into more focus on this library this week.

**Comment by babelshift** [comment]
I've just merged a pull request to address this. Every endpoint now returns an `ISteamWebResponse` object with the following properties:

- Data
- ContentLength
- ContentType
- ContentTypeCharSet
- Expires
- LastModififed

The `Data` property contains the deserialized response body.

Note that this pull request introduces breaking changes in that every endpoint's returned type has changed as noted above.

Please test, comment, and confirm when you can. Thanks.
