### ISSUE TITLE
Some game names have trailing spaces

### ISSUE THREAD

**Issue by kamranayub** [babelshift/SteamWebAPI2#5]
Subtle but noticed during an exact title match search--some games returned from the library appear to have trailing spaces. Specifically for my profile, Breath of Death VII (AppId: 107300) and a couple others. Visual Studio debugger shows name is `"Breath of Death VII "`

**Comment by babelshift** [comment]
Just curious, which endpoint did you use where you see this?

**Comment by kamranayub** [comment]
The IPlayerService GetOwnedGames

**Comment by babelshift** [comment]
This appears to be how the JSON is structured in the response on Valve's end. I usually don't like messing with the raw data in the event that someone wants to use it as it is in their own projects. But in this case, I can't imagine there being any purpose for a trailing space, so I'm thinking of just trimming before returning to the caller.

**Comment by kamranayub** [comment]
Yeah that's what I'd expect, I also don't know why that would be allowed.

**Comment by babelshift** [comment]
Fixed on commit https://github.com/babelshift/SteamWebAPI2/commit/68d88bc4deb9bc6592905f12a277b74801a727be

Please let me know if you see this happen on other endpoints.
