### ISSUE TITLE
[Bug] Filtering by AppIds in PlayerService.GetOwnedGamesAsync is not working

### ISSUE THREAD

**Issue by paprik** [babelshift/SteamWebAPI2#50]
According to the [Steam Web API documentation for `GetOwnedGames`](https://developer.valvesoftware.com/wiki/Steam_Web_API#GetOwnedGames_.28v0001.29), the App Ids cannot be passed as URL parameters and need to be given in JSON format.

If I looked correctly in `SteamWebRequest.BuildRequestCommand`, all parameters are currently translated into URL parameters.

**Comment by babelshift** [comment]
I tried to implement this, but I only get 500 Internal Server Error responses.

Here's an example (with key removed):

https://api.steampowered.com/IPlayerService/GetOwnedGames/v1/?key=<key>&include_played_Free_games=1&steamid=76561197960361544&include_appinfo=1&format=json&input_json=%7B%22appids_filter%22%3A%5B10%2C20%2C30%5D%7D

**Comment by paprik** [comment]
I think you have to put all the parameters in the JSON when you use the format, as in:
`{
"steamid":76561197960361544,
"appids_filter":[10,20,30]
}`

For example this works (key removed):
https://api.steampowered.com/IPlayerService/GetOwnedGames/v1/?key=XXXXX&format=json&input_json=%7B%0D%0A%22steamid%22%3A76561197960361544%2C%0D%0A%22appids_filter%22%3A%5B10%2C20%2C30%5D%0D%0A%7D

**Comment by babelshift** [comment]
Hey thanks. That worked!

**Comment by babelshift** [comment]
Fixed on commit afbc2186eed5b238813289a3bfd665beb22d33a6.
