### ISSUE TITLE
.Net Framework?

### ISSUE THREAD

**Issue by HurricanKai** [babelshift/SteamWebAPI2#53]
So, 4.0 isnt aviable for the .Net Framework.

at least it isnt on NuGet.

in the README it says
".Net Core is now Supported."

Any other support got removed?
Thanks for any help!

**Comment by babelshift** [comment]
The latest version of the SteamWebAPI2 NuGet package is compiled against .NET Standard 2.0. As described on the [.NET blog](https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-net-standard-2-0/), this allows you to install the library from .NET 4.6.1, .NET Core 2.0, Xamarin, and more.

Does that clear up any confusion?

**Comment by HurricanKai** [comment]
Yes thank you!

2017-11-06 1:57 GMT+01:00 Justin Skiles <notifications@github.com>:
