### ISSUE TITLE
Removed support for .Net version 4.5?

### ISSUE THREAD

**Issue by DallasLewis1996** [babelshift/SteamWebAPI2#58]
Hello,

I'm sorry if i'm just not understanding, but is there a reason support for this was removed? I'm currently trying to build a website using the steam API, and your library would help, as i'm not a very strong coder. Is there something that I can do on my end to make this work for me?

**Comment by babelshift** [comment]
The library is compiled against the .NET Standard 2.0 and supports all platforms which target that standard.

[According to Microsoft](https://docs.microsoft.com/en-us/dotnet/standard/net-standard), this library will work if your project targets .NET 4.6.1+, .NET Core 2.0, or other less common targets.

It should just be a matter targeting one of the supported frameworks in your project and using the nuget install commands as described in the README of this project.

**Comment by DallasLewis1996** [comment]
Oh, wow. Sorry the misunderstanding.

**Comment by DallasLewis1996** [comment]
So... I have updated my existing project to target .NET Framework 4.6.1 and I was still unable to install the library. For testing purposes I created a new project that targeted this framework from the start, and it still not work. I'll attach a screenshot of the project in hopes you'll see what i'm doing wrong.
![why](https://user-images.githubusercontent.com/27368680/35307518-4c55c486-0060-11e8-9c0a-559f5be15652.PNG)

**Comment by babelshift** [comment]
I created a new Console Application using VS2017 and made sure that it targets .NET 4.6.1.

I then typed `install-package SteamWebAPI2` in the Package Manager Console.

Here's the results:

```
Attempting to gather dependency information for package 'SteamWebAPI2.4.0.6' with respect to project 'TestSteamWebAPI2Nuget', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 577.89 ms
Attempting to resolve dependencies for package 'SteamWebAPI2.4.0.6' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'SteamWebAPI2.4.0.6'
Resolved actions to install package 'SteamWebAPI2.4.0.6'
Retrieving package 'AutoMapper 6.1.1' from 'nuget.org'.
Retrieving package 'Newtonsoft.Json 10.0.3' from 'nuget.org'.
Retrieving package 'Steam.Models 3.0.6' from 'nuget.org'.
Retrieving package 'SteamWebAPI2 4.0.6' from 'nuget.org'.
  GET https://api.nuget.org/v3-flatcontainer/steamwebapi2/4.0.6/steamwebapi2.4.0.6.nupkg
Adding package 'AutoMapper.6.1.1' to folder 'c:\users\justin\documents\visual studio 2017\Projects\TestSteamWebAPI2Nuget\packages'
Added package 'AutoMapper.6.1.1' to folder 'c:\users\justin\documents\visual studio 2017\Projects\TestSteamWebAPI2Nuget\packages'
  OK https://api.nuget.org/v3-flatcontainer/steamwebapi2/4.0.6/steamwebapi2.4.0.6.nupkg 313ms
Installing SteamWebAPI2 4.0.6.
Added package 'AutoMapper.6.1.1' to 'packages.config'
Successfully installed 'AutoMapper 6.1.1' to TestSteamWebAPI2Nuget
Adding package 'Newtonsoft.Json.10.0.3' to folder 'c:\users\justin\documents\visual studio 2017\Projects\TestSteamWebAPI2Nuget\packages'
Added package 'Newtonsoft.Json.10.0.3' to folder 'c:\users\justin\documents\visual studio 2017\Projects\TestSteamWebAPI2Nuget\packages'
Added package 'Newtonsoft.Json.10.0.3' to 'packages.config'
Executing script file 'c:\users\justin\documents\visual studio 2017\Projects\TestSteamWebAPI2Nuget\packages\Newtonsoft.Json.10.0.3\tools\install.ps1'
Successfully installed 'Newtonsoft.Json 10.0.3' to TestSteamWebAPI2Nuget
Adding package 'Steam.Models.3.0.6' to folder 'c:\users\justin\documents\visual studio 2017\Projects\TestSteamWebAPI2Nuget\packages'
Added package 'Steam.Models.3.0.6' to folder 'c:\users\justin\documents\visual studio 2017\Projects\TestSteamWebAPI2Nuget\packages'
Added package 'Steam.Models.3.0.6' to 'packages.config'
Successfully installed 'Steam.Models 3.0.6' to TestSteamWebAPI2Nuget
Adding package 'SteamWebAPI2.4.0.6' to folder 'c:\users\justin\documents\visual studio 2017\Projects\TestSteamWebAPI2Nuget\packages'
Added package 'SteamWebAPI2.4.0.6' to folder 'c:\users\justin\documents\visual studio 2017\Projects\TestSteamWebAPI2Nuget\packages'
Added package 'SteamWebAPI2.4.0.6' to 'packages.config'
Successfully installed 'SteamWebAPI2 4.0.6' to TestSteamWebAPI2Nuget
Executing nuget actions took 2.39 sec
Time Elapsed: 00:00:03.6142881
```

**Comment by ItsEddie** [comment]
The problem still exists as OP mentions. 

`
Install-Package : Could not install package 'SteamWebAPI2 4.0.8'. You are 
trying to install this package into a project that targets 
'.NETFramework,Version=v4.6.1', but the package does not contain any assembly 
references or content files that are compatible with that framework. For more 
information, contact the package author.
At line:1 char:1
+ Install-Package SteamWebAPI2
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManag 
   ement.PowerShellCmdlets.InstallPackageCommand
 `

**Comment by ItsEddie** [comment]
Okay, well, this is a post from January so I'm surprised it still hasn't been resolved. I'm experiencing the same problem as OP and regardless of whether I create an entirely new project targeting 4.6.1, or I upgrade/downgrade an existing project to that framework -- installing using Nuget does not work.

`Install-Package : Could not install package 'SteamWebAPI2 4.0.8'. You are 
trying to install this package into a project that targets 
'.NETFramework,Version=v4.6.1', but the package does not contain any assembly 
references or content files that are compatible with that framework. For more 
information, contact the package author.
At line:1 char:2
+  Install-Package SteamWebAPI2
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManag 
   ement.PowerShellCmdlets.InstallPackageCommand
 `

I'll probably just get a copy of the source code and add it but it's rather odd how this works for you but not for us.

**Comment by babelshift** [comment]
Please understand that this is a library that I work on in my free time between a full time job and parenting duties.

Are you using Visual Studio 2017? What type of project are you creating? Web app? Console app? Please provide some more exact specifics so I can hope to reproduce the issue.

**Comment by DallasLewis1996** [comment]
Hey, Babelshift. Long time no see. I haven't touched your API since I created this post since I was just using it for a College Project. Want me to close this to get it out of your hair? :)

**Comment by ItsEddie** [comment]
I'm using Microsoft Visual Studio 2017 and a regular console application. Not using .NET Core.

**Comment by ItsEddie** [comment]
I do apologize if I came over hasty. I just meant to say that I was surprised that the issue OP was having was not something temporary.
