### ISSUE TITLE
Support for publisher endpoints

### ISSUE THREAD

**Issue by sswires** [babelshift/SteamWebAPI2#63]
Hi,

This library seems very useful for interacting with the Steam API for public endpoints but there are however a lot of publisher endpoints for publishers of games on Steam. See here: https://partner.steamgames.com/doc/webapi

Some interfaces such as IGameInventory and IGameNotificationsService only contain methods that can be called with publisher keys. Other interfaces, such as ISteamApps have publisher-only functions such as GetAppBuilds.

Publishers can also use the https://partner.steam-api.com/ endpoint which doesn't have cached results. Calls to this endpoint must use a publisher key.

This would be a worthwhile enhancements for game developers wishing to use this library. Right now there are very few .NET Core compatible libraries abstracting the Steam Web API in this way.

**Comment by babelshift** [comment]
I would love to support this, but I have no access to the private endpoints
and thus could not test.

I would have to rely on pull requests or some developers trusting me with
their publisher keys.
