### ISSUE TITLE
Package does not contain any assembly references or content files that are compatible with that framework

### ISSUE THREAD

**Issue by SniperED007** [babelshift/SteamWebAPI2#64]
When trying to upgrade from version 3.1.04 to 4.0.8 I get this error:

Could not install package 'SteamWebAPI2 4.0.8'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

What should I do?

**Comment by babelshift** [comment]
Can you give more details about your project setup? I am not able to reproduce this. Here are the steps I took:

- Create new .NET 4.6.1 Console App
- `install-package SteamWebAPI2 -Version 3.1.04
- `update-package`

The update succeeds.

**Comment by SniperED007** [comment]
I'm using an ASP.NET Cloud Web API app

**Comment by babelshift** [comment]
Please re-open when you have more info.
