### ISSUE TITLE
Error Mapping Types - GetPublishedFileDetails Endpoint

### ISSUE THREAD

**Issue by Alexr03** [babelshift/SteamWebAPI2#65]
Hello,

I am receiving this error when trying to execute GetPublishedFileDetails. This is the StackTrace : https://i.Alexr03.com/aid33R1993NH.png

Any help would be appreciated!

**Comment by Alexr03** [comment]
Hello,

I am giving it a list<ulong> and thats it, I print the values to console and they are indeed correct.

**Comment by babelshift** [comment]
Please provide the exact values that can reproduce this problem.

I have attempted with my own values and cannot reproduce.

For example: `itemcount = ` and `publishedfileids[0] = 55555` does not cause a problem.

**Comment by babelshift** [comment]
Please re-open when you have more info.
