### ISSUE TITLE
Can't be installed on Mac OSX

### ISSUE THREAD

**Issue by SeeD-Seifer** [babelshift/SteamWebAPI2#7]
There is Mono on OSX and it does not support neither **dnx452** nor **dnx46** runtimes yet. See https://github.com/aspnet/aspnet-docker/issues/129 and https://github.com/aspnet/dnx/issues/3212.

Would be great to support **dnx451**.

**Comment by babelshift** [comment]
I'm not familiar with using Mono, OSX, and dnx runimes. Are you looking for support for .NET 4.5.1?

**Comment by SeeD-Seifer** [comment]
Right, I'm look at support for .NET 4.5.1, if possible.

**Comment by babelshift** [comment]
Please try the latest nuget package 1.1.0.28.

**Comment by SeeD-Seifer** [comment]
Awesome! That works, thank you.
