### ISSUE TITLE
GetServerSteamIDsByIP() returns null

### ISSUE THREAD

**Issue by xWolfx93** [babelshift/SteamWebAPI2#71]
Hello,

to quickly summarize i am trying to add a functionality to my discord bot to see if a given steam server is online. So i figured this API should do the trick, but i am getting no data back. and Yes the key is right, the sample usage from the Readme works fine.

attached is my code, i figure i am just doing something very wrong.
![grafik](https://user-images.githubusercontent.com/26422205/57607785-2473d700-756c-11e9-9718-e5bb85f052b1.png)

**Comment by babelshift** [comment]
And you're sure that your server is online?

It looks like there is a method on the Steam Web API that I never mapped to this library called `GetServersAtAddress`.

```
GET https://api.steampowered.com/ISteamApps/GetServersAtAddress/v1?addr=<ip_addr>
```

I'll try to get it added. In the meantime, you can try to hit that URL directly in your browser (obviously add your API KEY to the query string params) and see if you get results.

**Comment by babelshift** [comment]
Closing because no response to above question.

**Comment by 53m1k0l0n** [comment]
I'm not getting any data back. Even in the browser. Result always empty. "steamUserInterface.GetServerSteamIDsByIPAsync(ip)"

And yes the Servers are Online.

GET https://api.steampowered.com/ISteamApps/GetServersAtAddress/v1?addr=<ip_addr> works.
