### ISSUE TITLE
HttpClients not being handled correctly

### ISSUE THREAD

**Issue by dukeofsussex** [babelshift/SteamWebAPI2#72]
Great library, but diving into the code I found a lot of this:

```csharp
HttpClient httpClient = new HttpClient();
// do something
return response;
```

The client isn't being disposed off, kept as a singleton or injected using the [factory pattern](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests).

I have no clue whether this causes any issues though, just a heads up.

**Comment by babelshift** [comment]
Fixed with #73
