### ISSUE TITLE
Steam User login pass dev key

### ISSUE THREAD

**Issue by kyilintun2017** [babelshift/SteamWebAPI2#75]
can't use this function.
var steamInterface = new SteamUser("<devKeyHere>");
the class has
SteamUser(ISteamWebRequest steamWebRequest, ISteamWebInterface steamWebInterface = null);

Please kindly give advise.

Error message: Cannot convert from 'string' to 'SteamWebAPI2.Utilities.ISteamWebRequest'

**Comment by kyilintun2017** [comment]
No longer needed.

**Comment by babelshift** [comment]
Duplicate of #74

**Comment by babelshift** [comment]
Fixed by #76
