### ISSUE TITLE
SteamStore not working

### ISSUE THREAD

**Issue by mrousavy** [babelshift/SteamWebAPI2#81]
I can't seem to find a way to use the `SteamStore` API.

I tried initializing it via the `webInterfaceFactory.CreateSteamWebInterface<T>` factory method, and via it's default constructor, but nothing seems to work.

![devenv_2019-12-09_20-12-57](https://user-images.githubusercontent.com/15199031/70465113-8673cb00-1ac0-11ea-8902-514137060813.png)

![devenv_2019-12-09_20-15-16](https://user-images.githubusercontent.com/15199031/70465150-9d1a2200-1ac0-11ea-8bfe-552eacd58e83.png)

I'm just trying to find out whether a game has multiplayer/coop support or not.

Thanks!

**Comment by babelshift** [comment]
@mrousavy the `SteamStore` interface is admittedly poorly written and not following the same patterns as the rest of the SDK.

Your second approach should work, but I don't think the appid you're using has any information tied to it. You can bypass my SDK and hit the Steam Store API directly to confirm.

https://store.steampowered.com/api/appdetails/?appids=216938

The above returns `success: false`.

**Comment by CriticalFlaw** [comment]
I'm having the same issue with **EconItems**. Is there a workaround for it as well or am I doing something wrong?

`var steam = SteamInterface.CreateSteamWebInterface<EconItems>(new HttpClient(), EconItemsAppId.TeamFortress2);`

**Comment by babelshift** [comment]
@CriticalFlaw EconItems has to be constructed with the overloaded `CreateSteamWebInterface` method that takes in an `EconItemsAppId` to identify which application your requests will be for. I know, not very intuitive. I'm thinking of a way to make this better.

**Comment by CriticalFlaw** [comment]
That did it. Such a silly thing for me to miss. Thank you!

**Comment by babelshift** [comment]
Closing due to no comment from issue author. Please re-open if necessary.
