### ISSUE TITLE
SteamId constructor fails if a numeric vanity ID is used

### ISSUE THREAD

**Issue by slinkayy** [babelshift/SteamWebAPI2#89]
In the case of https://steamcommunity.com/id/12345 and similar, [the SteamId(string value, ISteamWebRequest steamWebRequest) constructor will attempt to parse it as as 64-bit Steam ID](https://github.com/babelshift/SteamWebAPI2/blob/db4821194aea8bd375c684b77466cbbcfe279256/src/SteamWebAPI2/Models/SteamId.cs#L259).

Would be better to check what uriResult.Segments[1] is and resolve based on that.

**Comment by babelshift** [comment]
@slinkayy thanks for this. I'll check it out today/tomorrow.
